spring:
  datasource: 
    url: jdbc:mysql://${your.host}/${your.db}
    username: ${your.username}
    password: ${your.password}
    driver-class-name: org.gjt.mm.mysql.Driver
  redis: 
    database: 3
    host: ${your.host}
    port: 6379
    password: 
    timeout: 0
    pool: 
      max-active: 8
      max-idle: 8
      min-idle: 0
      max-wait: -1
    
    
#mybatis:
#  config-location: classpath:mybatis-config.xml

your:
  host: 127.0.0.1
  db: mysql
  username: root
  password: 123456

#spring:
# datasource: 
#   url: jdbc:h2:mem:test
#   username: root
#   password: 123456
#   driver-class-name: org.h2.Driver
#   schema: classpath:schema.sql
#   data: classpath:data.sql
 

  
    